import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { env } from "./config/env.js";
import { errorHandler, notFound } from "./middleware/errors.js";
import { authRouter } from "./routes/auth.js";
import { gradientsRouter } from "./routes/gradients.js";
import { projectsRouter } from "./routes/projects.js";
import { publicRouter } from "./routes/public.js";

export const app = express();
app.set("trust proxy", 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: "100kb" }));
app.use(cookieParser());
app.use("/api/auth", rateLimit({ windowMs: 15 * 60 * 1000, limit: 40, standardHeaders: "draft-7", legacyHeaders: false }), authRouter);
app.get("/api/health", (_request, response) => response.json({ success: true, data: { status: "ok", timestamp: new Date().toISOString() } }));
app.use("/api/projects", projectsRouter);
app.use("/api/gradients", gradientsRouter);
app.use("/api", publicRouter);
app.use(notFound);
app.use(errorHandler);
